apiVersion: v1
kind: Service
metadata:
  name: {{ template "conode.fullname" . }}-headless
  labels:
    app: {{ template "conode.name" . }}
    chart: {{ template "conode.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp1
      port: {{ .Values.service.ports.tcp1 }}
      targetPort: tcp1
      protocol: TCP
    - name: tcp2
      port: {{ .Values.service.ports.tcp2 }}
      targetPort: tcp2
      protocol: TCP
  selector:
    app: {{ template "conode.name" . }}
    release: "{{ .Release.Name }}"
