apiVersion: v1
kind: Secret
metadata:
  name: {{ template "conode.fullname" . }}
  labels:
    app: {{ template "conode.name" . }}
    chart: {{ template "conode.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  private.toml: {{ .Values.privateToml | b64enc | quote }}
